### ISSUE TITLE
Incomplete DBFT Description.

### ISSUE THREAD

**Issue by mryoso1994** [xcash-rocks/xcash-website#1]
![Screenshot_14](https://user-images.githubusercontent.com/25314226/169980091-8d798d97-1bc1-4a39-b824-3eeb21bbeaf3.png)

**Comment by Cacocoin** [comment]
Thank you, will update this asap.

**Comment by Cacocoin** [comment]
Removed DBFT placeholder from this section, and added more to the DPOPS section.
