### ISSUE TITLE
Spelling and wordging change suggestions.

### ISSUE THREAD

**Issue by Zurginator** [xcash-rocks/xcash-website#11]
To modernise Monero for the Web3, the following technological pillars were built upon:
to
To modernize Monero for the Web3, the following technological pillars were built upon:

Rethinking DPOS with an optimised CryptoNote
to
Rethinking DPOS with an optimized CryptoNote

Will talk directly regarding some of the phrasings.

**Comment by Cacocoin** [comment]
British English: optimised,  modernise 
American English: optimized, modernize

I'll change them to the American variants, however, they aren't spelling issues.
