### ISSUE TITLE
Quickswap.exchange Link Error

### ISSUE THREAD

**Issue by mryoso1994** [xcash-rocks/xcash-website#2]
ipfs resolve -r /ipns/info.quickswap.exchange/pair/0x30167fea9499c11795bfd104667240bdac939d3a: no link named "pair" under QmTnm154Fc7u1xg9VhUQGNc8UGRk3yB6rpxwZi67Yq7gAH
![Screenshot_15](https://user-images.githubusercontent.com/25314226/170027666-4c7298e2-fa10-477e-86ff-6c181e6c8135.png)
![Screenshot_18](https://user-images.githubusercontent.com/25314226/170040304-4422ee5b-a29a-4bf9-bf83-b06867d6666b.png)

**Comment by xcash-rocks** [comment]
Thanks @mryoso1994  for finding this!
