### ISSUE TITLE
Exchanges text is not Visible/ Microsoft Edge Browser

### ISSUE THREAD

**Issue by mryoso1994** [xcash-rocks/xcash-website#3]
![Screenshot_16](https://user-images.githubusercontent.com/25314226/170031941-8d9db693-f40a-4942-9f65-da90efc0ddae.png)

**Comment by Cacocoin** [comment]
@mryoso1994 also tested on Windows 10 Edge Version 101.0.1210.53 (Official build) (64-bit). Are there any other SVGs which aren't displaying?

**Comment by mryoso1994** [comment]
> @mryoso1994 also tested on Windows 10 Edge Version 101.0.1210.53 (Official build) (64-bit). Are there any other SVGs which aren't displaying?

Microsoft Edge
Version 101.0.1210.53 (Official build) (64-bit) thats the only part that are not displaying

**Comment by mryoso1994** [comment]
i also tried InPrivate Incognito/ Same issu
![Screenshot_25](https://user-images.githubusercontent.com/25314226/171079235-9005b99f-d212-4f7b-973a-04161c226978.png)
e

**Comment by mryoso1994** [comment]
![Screenshot_26](https://user-images.githubusercontent.com/25314226/171079804-0be3026a-6ce6-4839-8160-9d43417ff384.png)
I highlighted to check if it was going to show but it still doesn't.

**Comment by xcash-rocks** [comment]
@mryoso1994 strange ... could you check if the image (svg) url is working in edge? e.g: https://websitexf.xcash.rocks/assets/images/partners/5f72164dfa34506ed9ddb079_stex_orange.svg

Thank you!

![grafik](https://user-images.githubusercontent.com/71294927/171282844-1519e019-587d-47f7-9de6-a7924b83c02a.png)

**Comment by mryoso1994** [comment]
yes its working
![Screenshot_30](https://user-images.githubusercontent.com/25314226/171306770-a2aaf0bd-c519-4dc1-836c-22722e13df60.png)
.

**Comment by xcash-rocks** [comment]
todo's:
- [test in incognito mode] 
- [ask google]

**Comment by xcash-rocks** [comment]
i can't reconstruct the bug, in any setting the svg's get displayed ...
I guess I need to boot windows ;-P

**Comment by Cacocoin** [comment]
@mryoso1994  are you running with any extensions/ plugins?

**Comment by Cacocoin** [comment]
@mryoso1994 are you running with any extensions?

**Comment by mryoso1994** [comment]
> @mryoso1994 are you running with any extensions?

im not running any extensions.
