### ISSUE TITLE
[ENH] Add Cli wallet for raspberry

### ISSUE THREAD

**Issue by AnimusXCASH** [xcash-rocks/xcash-website#6]
Mario (Discord) has built wallet for raspberry. Tested on raspberry pi running ubuntu server 20.4 

Perhaps we should integrate that as well under wallet download section

here is the link to repo:
https://github.com/IdzaMeMario/xcash/tree/main/ubuntu2004rpi4

**Comment by xcash-rocks** [comment]
@IdzaMeMario nice !!!

**Comment by Cacocoin** [comment]
Closing as this request has been fulfilled.
