### ISSUE TITLE
[ENH] Link to Python library wrapper arround XCASH ecosystem rest Api's and wallet

### ISSUE THREAD

**Issue by AnimusXCASH** [xcash-rocks/xcash-website#7]
Maybe add this link: https://github.com/X-CASH-official/XCASH-Ecosystem-api-wrapper or https://pypi.org/project/xcash/ under the tools somewhere? In future ill work on other libraries (I hope someone else also) so we can provide easy access to developers

**Comment by Cacocoin** [comment]
I created a section for XPy-API that I need to find. I'll add it as soon as.

**Comment by Cacocoin** [comment]
![xpyfound](https://user-images.githubusercontent.com/98527172/171416631-f670712b-7d77-4a6d-a307-146a6864c902.png)
Found it, though it needs some work.

**Comment by AnimusXCASH** [comment]
Not a rush cause i still need to restructure it a bit

**Comment by Cacocoin** [comment]
X-PY section added and mostly complete. Closed due to initial issue seeming to be solved.
