### ISSUE TITLE
Service file not being used?

### ISSUE THREAD

**Issue by zachhildreth** [xcash-rocks/xcash-website#8]
is anything from this file being used in this website?
https://github.com/xcash-rocks/xcash-website/blob/master/src/app/services/http-request.service.ts

**Comment by Cacocoin** [comment]
I believe this is for the metrics section.

![metrics](https://user-images.githubusercontent.com/98527172/172063698-47f84861-684f-46c1-8a1a-dc9710c6f06f.png)

**Comment by xcash-rocks** [comment]
yes, http-request.service.ts is used for the metrics section

**Comment by xcash-rocks** [comment]
@zachhildreth why do you ask or can we close that issue?

**Comment by Cacocoin** [comment]
This should be solved. Closed due to inactivity.
